// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzvO3REUg3wY6GFS7dFoPJMddjUlKGYPY',
    appId: '1:208224290240:web:77e8b16797d3846d87b425',
    messagingSenderId: '208224290240',
    projectId: 'codelabmod3-17cd0',
    authDomain: 'codelabmod3-17cd0.firebaseapp.com',
    storageBucket: 'codelabmod3-17cd0.appspot.com',
    measurementId: 'G-5PYCBHXVJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMzAbnDBKi7j10_AyK9X4avRxIsVCeTTU',
    appId: '1:208224290240:android:5945de4efc09c18087b425',
    messagingSenderId: '208224290240',
    projectId: 'codelabmod3-17cd0',
    storageBucket: 'codelabmod3-17cd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClrxLWBidtsitDQhPfw1zdFpj2gYocio0',
    appId: '1:208224290240:ios:3ec0cb0e7345fbe087b425',
    messagingSenderId: '208224290240',
    projectId: 'codelabmod3-17cd0',
    storageBucket: 'codelabmod3-17cd0.appspot.com',
    iosBundleId: 'codelabmod3.com.codelabmod3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClrxLWBidtsitDQhPfw1zdFpj2gYocio0',
    appId: '1:208224290240:ios:3ec0cb0e7345fbe087b425',
    messagingSenderId: '208224290240',
    projectId: 'codelabmod3-17cd0',
    storageBucket: 'codelabmod3-17cd0.appspot.com',
    iosBundleId: 'codelabmod3.com.codelabmod3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzvO3REUg3wY6GFS7dFoPJMddjUlKGYPY',
    appId: '1:208224290240:web:35079b2e6d1ff53c87b425',
    messagingSenderId: '208224290240',
    projectId: 'codelabmod3-17cd0',
    authDomain: 'codelabmod3-17cd0.firebaseapp.com',
    storageBucket: 'codelabmod3-17cd0.appspot.com',
    measurementId: 'G-86J50Q3N8Y',
  );
}
